### ISSUE TITLE
For help

### ISSUE THREAD

**Issue by lanjiachuan** [muaz-khan/cordova-mobile-apps#4]
Author: hello, thank you for your help again, and I think the current demand is set up a video chat system, have the function of video conference system at the same time, if I use your this system, I should how to set up a complete environment, such as what I need to install the service, to achieve a goal

I according to you provide the code to compile the android platform is ok, but the ios added iosrtc increased the permissions will not be able to video, please help to solve it Thank you very much

**Comment by muaz-khan** [comment]
@lanjiachuan I'm planning to focus only on android in the moment. I wanna upgrade/improve all existing app-samples to support chats, rooms-management and other good features e.g. push-notification etc.

iOS can be added any time. Actually iOS-store doesn't accepts our apps until if we support ipv6.  Ipv6 should not only be enabled on TURN-level but also on socket.io level as well.

Do you have features list for specific apps? I mean are you planning to add "CHAT" or "File-Sharing" or ONLINE/OFFLINE icons or USERS-LIST or ROOMS-LIST or app's home-screen layout i.e. how videos should be displayed/rendered?
